### PR TITLE
fix(parsers): update nix definitions

### PR DESCRIPTION
**Pull request by treed**
Updates nix expressions to correspond with changes in https://github.com/cstrahan/tree-sitter-nix/commit/14af97221e59b355e421f71f94bf302f860267a8

### CODE REVIEW

**Comment by jcs090218** [comment]
Hi, thanks for contributing to `ts-fold`!

Does it work? The `tree-sitter-langs` package is still using the older version https://github.com/cstrahan/tree-sitter-nix/commit/6d6aaa50793b8265b6a8b6628577a0083d3b923d on Nov 29, 2021. We should update the submodules there before we get this merge!

**Comment by treed** [comment]
Hi!

It was required for it to work for me, using epkgs.{tree-sitter, tree-sitter-langs, tsc} from nixos 22.11 (and emacs-overlay, but as far as I can see, its only mention of tree-sitter is in the buildinputs for emacs 29+).

I wonder if the emacs package use a different version from the top-level tree-sitter-langs.

It's possible that I have something else going on that gave me a different version. If it matters, my flake.lock has:

emacs-overlay at         "rev": "9fe20594a0dce5fdba2f683d2c4cba3371ce7581",
nixpkgs at         "rev": "899e7caf59d1954882a8e2dff45ccc0387c186f6",

And the grammar in my store is  /nix/store/a2b2n2l3l8l5zcdjkvc8p29qpv6hc7x6-tree-sitter-nix-grammar-0.20.7/

I *also* have an issue with tree-sitter-rust not working because of an ABI mismatch, so I wouldn't be entirely surprised. Although as far as I can tell, tree-sitter versioning is a little messy.

I'm also content for this to hang out until all the necessary changes have happened elsewhere. I have this adjusted via setf in my init for the time being.

I also did my own package for ts-fold, as I didn't see it in nixpkgs anywhere:

```nix
          (let
            rev = "85db0117ead108213cc2a4210f72746d8ad8d20a";
          in
            epkgs.melpaBuild {
              pname = "ts-fold";
              version = "20221210.0";

              commit = rev;

              src = pkgs.fetchFromGitHub {
                owner = "emacs-tree-sitter";
                repo = "ts-fold";
                inherit rev;
                sha256 = "sha256-Ss1FWOq51+0FQpQWXPiSWHmNYU6NurUvI2wAjOGV/kA=";
              };

              recipe = pkgs.writeText "recipe" ''
                (ts-fold :fetcher github :repo "emacs-tree-sitter/ts-fold")
              '';
            })
```

(Notably doesn't include dependencies.)

**Comment by treed** [comment]
I also realized after commenting that this isn't actually a nix-related repo despite my PR being nix-related. Whoops. Sorry if much of that was nonsense for you. As mentioned, I'll look into if there's any special stuff happening with the package.

**Comment by jcs090218** [comment]
Hmmm, AFAIK `tree-sitter-langs` brings his own submodule to compile and ensures the compatibility to `emacs-rs-module` in https://github.com/emacs-tree-sitter/tree-sitter-langs/tree/master/repos.

> I also did my own package for ts-fold, as I didn't see it in nixpkgs anywhere:

This package isn't on MELPA, so this seems about right?

> I also realized after commenting that this isn't actually a nix-related repo despite my PR being nix-related. Whoops. Sorry if much of that was nonsense for you. As mentioned, I'll look into if there's any special stuff happening with the package.

No worries! ❤️

**Comment by treed** [comment]
Okay, I tracked it down. (Through several levels of indirection.)

Looks like nix's tree-sitter packages do just use their own version sets of grammars. The one for nix (as of current master) is:

```json
{
  "url": "https://github.com/cstrahan/tree-sitter-nix",
  "rev": "1b69cf1fa92366eefbe6863c184e5d2ece5f187d",
  "date": "2022-09-29T23:30:43-05:00",
  "path": "/nix/store/m5g4d7vddlwhhbdmzpwdvisqvb1hbh02-tree-sitter-nix",
  "sha256": "0ls9djhpbbnjvd6b3166zjy92di0927f70720b57j2d3925538i5",
  "fetchLFS": false,
  "fetchSubmodules": false,
  "deepClone": false,
  "leaveDotGit": false
}
```

This is from the top-level tree-sitter packages, which the emacs package is overridden with.

So, it looks like nixpkgs does have a newer version than the official emacs package. I guess this PR can wait until it updates, and hopefully if other nix users run into issues, they'll find this too.

In the meantime, my modification handles it for me:

```emacs-lisp
  (setf (alist-get 'nix-mode ts-fold-range-alist)
	'((attrset_expression . ts-fold-range-seq)
	  (interpolation . ts-fold-range-seq)
	  (list_expression . ts-fold-range-seq)))
  (setf (alist-get 'nix-mode ts-fold-foldable-node-alist)
	'(list_expression interpolation attrset_expression))
```

**Comment by jcs090218** [comment]
You can try to open a PR in [tree-sitter-langs](https://github.com/emacs-tree-sitter/tree-sitter-langs) to bump the grammar repo submoudule (`repos/nix`). Few example PR, 

* https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/149
* https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/110

It should be pretty easy to do. Or open an issue for feature request should work as well.

cc @meain

**Comment by meain** [comment]
I've opened a PR to bump nix grammar at https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/177

**Comment by talw** [comment]
Since:
- https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/177 is merged
- https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/master/CHANGELOG.md#01219---2023-06-20 seems to have been released
 
Perhaps we can proceed with merging this PR?

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Thanks to everyone who participate in this PR! ❤️ 😁

**Pull request merged**
