### PR TITLE
Added support for case_clause, otherwise_clause, elseif_clause, and else_clause to fold independently for matlab-mode

### PR DESCRIPTION
**Pull request by Nidish96**
Added support for the clauses listed above to fold independently of their parents. 

Also caught a couple repeated entries (maybe due to erroneous merging from github, but its fixed).

### CODE REVIEW

**Comment by jcs090218** [comment]
Can you rebase this? Thanks!

**Comment by Nidish96** [comment]
Done!

**Comment by jcs090218** [comment]
Hmmm... I am not able to merge. 🤔

**Comment by Nidish96** [comment]
I'm not sure what's going on... my repo says that my master is not behind upstream.

Maybe its some setting from your side? I found some info online about rebasing: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-rebasing-for-pull-requests

**Comment by jcs090218** [comment]
Ah, okay. This is the first time I have encountered this issue. You cannot rebase and merge; instead, you can squash and merge. 🤔

**Pull request merged**
